
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/supabase-types';

const SUPABASE_URL = "https://emzvyaqhpchhxxppxaar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtenZ5YXFocGNoaHh4cHB4YWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzQwMTQsImV4cCI6MjA1OTUxMDAxNH0.TDFB9hSJ216jXOjDrBzsPD9PyRRLRac8jmf6_zERKwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
